# Generated by Django 4.1.7 on 2023-03-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=4)),
                ('Genre1', models.CharField(max_length=50)),
                ('Genre2', models.CharField(blank=True, max_length=50, null=True)),
                ('Genre3', models.CharField(blank=True, max_length=50, null=True)),
                ('Director', models.CharField(max_length=50)),
                ('Cast1', models.CharField(max_length=50)),
                ('Cast2', models.CharField(max_length=50)),
                ('Cast3', models.CharField(max_length=50)),
                ('Cast4', models.CharField(max_length=50)),
            ],
        ),
    ]
